apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-ldap
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-ldap
  template:
    metadata:
      labels:
        app: circleguard-ldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        env:
        - name: LDAP_ORGANISATION
          value: "CircleGuard"
        - name: LDAP_DOMAIN
          value: "circleguard.edu"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-ldap
  namespace: dev
spec:
  selector:
    app: circleguard-ldap
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: ldaps
    port: 636
    targetPort: 636
