apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-promotion-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-promotion-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        readinessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-dev-postgresql.dev.svc.cluster.local:5432/circleguard_promotion"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "supersecretpassword"
        - name: SPRING_NEO4J_URI
          value: "bolt://neo4j-dev.dev.svc.cluster.local:7687"
        - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
          value: "neo4j"
        - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
          value: "password"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-dev.dev.svc.cluster.local:9092"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-dev-master.dev.svc.cluster.local"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          value: "my-super-secret-dev-key-32-chars-long-12345678"
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_NEO4J_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
          value: "0"
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-promotion-service
  namespace: dev
spec:
  selector:
    app: circleguard-promotion-service
  ports:
  - port: 80
    targetPort: 8088
