apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-file-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-file-service
  template:
    metadata:
      labels:
        app: circleguard-file-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-file-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-file-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-file-service
  namespace: dev
spec:
  selector:
    app: circleguard-file-service
  ports:
  - port: 80
    targetPort: 8085
