apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-form-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-form-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        readinessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-dev-postgresql.dev.svc.cluster.local:5432/circleguard_form?sslmode=disable"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "supersecretpassword"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-dev.dev.svc.cluster.local:9092"
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "none"
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
        - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
          value: "0"
        - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-form-service
  namespace: dev
spec:
  selector:
    app: circleguard-form-service
  ports:
  - port: 80
    targetPort: 8086
