apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-notification-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-notification-service
  template:
    metadata:
      labels:
        app: circleguard-notification-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-notification-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-dev.dev.svc.cluster.local:9092"
        - name: SPRING_MAIL_HOST
          value: "localhost"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_MAIL_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
          value: "false"
        - name: AUTH_API_URL
          value: "http://circleguard-auth-service.dev.svc.cluster.local"
        - name: JWT_SECRET
          value: "my-super-secret-dev-key-32-chars-long-12345678"
        - name: QR_SECRET
          value: "my-qr-secret-key-for-dev-1234567890"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-notification-service
  namespace: dev
spec:
  selector:
    app: circleguard-notification-service
  ports:
  - port: 80
    targetPort: 8082
