apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity-service
  namespace: stage
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-identity-service
  template:
    metadata:
      labels:
        app: circleguard-identity-service
    spec:
      containers:
      - name: circleguard-identity-service
        image: circle-guard/circleguard-identity-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://host.minikube.internal:5434/circleguard_identity"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: circleguard-stage-secrets
              key: DB_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: circleguard-stage-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-stage-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-identity-service
  namespace: stage
spec:
  selector:
    app: circleguard-identity-service
  type: NodePort
  ports:
  - port: 80
    targetPort: 8083
