apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-notification-service
  namespace: stage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: circleguard-notification-service
  template:
    metadata:
      labels:
        app: circleguard-notification-service
    spec:
      containers:
      - name: circleguard-notification-service
        image: circle-guard/circleguard-notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "host.minikube.internal:9092"
        - name: SPRING_MAIL_HOST
          value: "host.minikube.internal"
        - name: AUTH_API_URL
          value: "http://circleguard-auth-service.stage.svc.cluster.local"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-stage-secrets
              key: JWT_SECRET
        - name: QR_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-stage-secrets
              key: QR_SECRET
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_LDAP_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_MAIL_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-notification-service
  namespace: stage
spec:
  selector:
    app: circleguard-notification-service
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
