apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-gateway-service
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-gateway-service
  template:
    metadata:
      labels:
        app: circleguard-gateway-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-gateway-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-gateway-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8087
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          tcpSocket:
            port: 8087
          initialDelaySeconds: 120
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-dev-master.dev.svc.cluster.local"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-production-secrets
              key: JWT_SECRET
        - name: QR_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-production-secrets
              key: QR_SECRET
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_LDAP_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_MAIL_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
          value: "false"
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-gateway-service
  namespace: production
spec:
  selector:
    app: circleguard-gateway-service
  type: NodePort
  ports:
  - port: 80
    targetPort: 8087
