apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-notification-service
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-notification-service
  template:
    metadata:
      labels:
        app: circleguard-notification-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: circleguard-notification-service
        image: circleguardacrcore.azurecr.io/circle-guard/circleguard-notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "128Mi"
            cpu: "1m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-dev.dev.svc.cluster.local:9092"
        - name: SPRING_MAIL_HOST
          value: "localhost"
        - name: AUTH_API_URL
          value: "http://circleguard-auth-service.production.svc.cluster.local"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-production-secrets
              key: JWT_SECRET
        - name: QR_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-production-secrets
              key: QR_SECRET
        - name: MANAGEMENT_HEALTH_DATASOURCE_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_LDAP_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_MAIL_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "false"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
          value: "false"
        - name: SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-notification-service
  namespace: production
spec:
  selector:
    app: circleguard-notification-service
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
